id: PB1A54BD4
initial_creation_type: input
source_metadata:
  title: Longchen Rabjam Series
  language: es
  description: 'Texts by and about Longchen Rabjam (klong chen rab ''byams, 1308-1364),
    also known as Drimé Özer (dri med ''od zer), who is widely acknowledged as the
    greatest exponent of Dzogpachenpo, or the Great Perfection, in Tibetan history:'
  volume:
    7535b4219cdc4d15b30bb8d66ef89891:
      title: 'A Mirror Revealing the Crucial Points: Advice on the Ultimate Meaning'
      parent: Advice
    a4a8e5bb9b854936a4996f1bf838e06c:
      title: 'A Wish-Fulfilling Gem: Guidance on the Meaning of Being at Ease with
        Illusion, A Dzogchen Teaching'
      parent: Advice
    4d513a4acdfe4b74abd004230bbf80d8:
      title: 'Crucial Advice: A Complete Set of Instructions for the Bardos'
      parent: Advice
    7452eff7050c4331b8a127204fea8e80:
      title: Song of the Enchanting Wildwoods
      parent: Advice
    b085922811b54f83ae867e640fc22966:
      title: Thirty Pieces of Heart Advice
      parent: Advice
    a953a6efb4564c0e94a0cb11730136d0:
      title: 'From ''Finding Comfort and Ease in Meditation'': A Guide to Locations
        for Cultivating Samadhi'
      parent: Meditation
    c24956470b3342daa0a56ba6170ab332:
      title: 'From ''Finding Comfort and Ease in Meditation'': The Practitioner of
        Meditation'
      parent: Meditation
    a220155c24dd41839dd268226aca3422:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Guru Rinpoche Prayers
    ccd21508beb44ccca555607cc4b1bd9b:
      title: Guru Yoga of the Great Omniscient One, Longchenpa
      parent: Guru Yoga
    7302cc6ff22647ec8175a41557d9eadb:
      title: 'Rain of Wisdom, Love and Spiritual Power: A Guru Yoga of the Three Mañjughoṣas
        of the Land of Snow'
      parent: Guru Yoga
    51c8c4d6af144be59886f221e4d834b8:
      title: Prayer to Longchenpa (Adapted from the Words of Mipham Rinpoche)
      parent: Lineage Prayers
    325799d99e5e4914a2c52369883991f6:
      title: Prayer to the Omniscient Longchen Rabjam
      parent: Lineage Prayers
    247d297d64c445c282bab510bdd894e6:
      title: In Praise of Longchenpa – The Greatness of the Omniscient Longchen Rabjam
      parent: Praise
    611744d3c0304eb4a6cfd789d341be85:
      title: Dedication (Sangye tenpa...)
      parent: Prayers
    8403862e3930424582a4388c89b7b009:
      title: Food Offering Prayer
      parent: Prayers
    96cdcbd0bf4b41f9a18ca3f9fd1154b7:
      title: 'Gyang Lu: A Song of Calling from Afar'
      parent: Prayers
    4e57260e4aae4a4dada3dfe92a235589:
      title: 'The Pure Three Kāyas Ablaze in Perfect Splendour: A Prayer Based on
        the Meaning of the Great Perfection'
      parent: Prayers
    0b8e0f69cce045ce8b41832d1022b392:
      title: Prayer and Call from Afar to the Great Omniscient One
      parent: Calling the Guru from Afar
    d14a5e44e2774197b35f17f223ff17f1:
      title: The Song of the Vajra
      parent: Songs
created_at: '2022-03-01T00:41:21.599990'
last_modified_at: '2022-03-01T00:41:21.599993'
